listen: 0.0.0.0:443
vhosts:
  - name: "%ADDRESS%"
    tlsoffloading: true
    managedcert: true
    alpn: h2,http/1.1
    protocols: tls12,tls13
    http:
      handler: fileServer
      args: /var/www/html
    default:
      handler: proxyPass
      args: unix:@v2ray.sock
